node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   
   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v2/', 'pegasus120mouan') {
       def app = docker.build("pegasus120mouan/docker-nodejs-demo:${commit_id}", '.').push()
     }
   }
}
